<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="ReviewedDeploymentRoot.fs" />
    <Compile Include="AdministrationTypes.fs" />
    <Compile Include="Baseline.fs" />
    <Compile Include="SchemaDefinition.fs" />
    <Compile Include="SchemaAdmission.fs" />
    <Compile Include="Preparations.fs" />
    <Compile Include="PreparationIntegrity.fs" />
    <Compile Include="RuntimeAccessPolicy.fs" />
    <Compile Include="RuntimeAcl.fs" />
    <Compile Include="RuntimeConstraintPolicy.fs" />
    <Compile Include="CatalogManifest.fs" />
    <Compile Include="RuntimeSchema.fs" />
    <Compile Include="DatabaseEnvironment.fs" />
    <Compile Include="RuntimeDatabase.fs" />
    <Compile Include="AuthorityOperationFence.fs" />
    <Compile Include="ScalarEncoding.fs" />
    <Compile Include="Sql.fs" />
    <Compile Include="CaseErasureSuppression.fs" />
    <Compile Include="ActorGrantCandidate.fs" />
    <Compile Include="CaseMutationCommitHealth.fs" />
    <Compile Include="ActorGrantRead.fs" />
    <Compile Include="ActorGrantGateQueries.fs" />
    <Compile Include="ActorGrantGateBinding.fs" />
    <Compile Include="ActorGrantImportGate.fs" />
    <Compile Include="ActorGrantTombstoneGate.fs" />
    <Compile Include="ActorGrantGate.fs" />
    <Compile Include="PreparationEvidence.fs" />
    <Compile Include="WitnessEventIdentity.fs" />
    <Compile Include="WitnessCandidate.fs" />
    <Compile Include="WitnessFailures.fs" />
    <Compile Include="WitnessProof.fs" />
    <Compile Include="WitnessCustodyAdmission.fs" />
    <Compile Include="WitnessPrimaryMatch.fs" />
    <Compile Include="WitnessIntentAdmission.fs" />
    <Compile Include="WitnessSettlement.fs" />
    <Compile Include="WitnessProtocol.fs" />
    <Compile Include="InstallationUseScopeRead.fs" />
    <Compile Include="WitnessProtocolHandoff.fs" />
    <Compile Include="WitnessAcceptedProtocol.fs" />
    <Compile Include="WitnessProtocolReconciliation.fs" />
    <Compile Include="WitnessTechnical.fs" />
    <Compile Include="WitnessTechnicalStartReconcile.fs" />
    <Compile Include="WitnessTechnicalCandidateRead.fs" />
    <Compile Include="RecoveryArtifactExportCandidate.fs" />
    <Compile Include="RecoveryArtifactExportTypes.fs" />
    <Compile Include="RecoveryArtifactExportRead.fs" />
    <Compile Include="RecoveryArtifactExportWrite.fs" />
    <Compile Include="ManagedCopyEventHash.fs" />
    <Compile Include="ManagedCopySignerCandidate.fs" />
    <Compile Include="ManagedCopySignature.fs" />
    <Compile Include="InstallationLossRetirementCandidate.fs" />
    <Compile Include="InstallationLossOperationSet.fs" />
    <Compile Include="InstallationLossRetirementWitness.fs" />
    <Compile Include="InstallationLossRetirementPrimary.fs" />
    <Compile Include="ManagedCopyInventoryDigest.fs" />
    <Compile Include="BackupHealthCanonical.fs" />
    <Compile Include="BackupHealthTypes.fs" />
    <Compile Include="BackupHealthQualification.fs" />
    <Compile Include="BackupHealthFields.fs" />
    <Compile Include="BackupHealthDocumentParts.fs" />
    <Compile Include="BackupHealthCertificate.fs" />
    <Compile Include="BackupHealthPolicyCodec.fs" />
    <Compile Include="BackupHealthRuntimeCopies.fs" />
    <Compile Include="BackupHealthRuntimeWalCoverage.fs" />
    <Compile Include="BackupHealthRuntimeAuthority.fs" />
    <Compile Include="BackupHealthRuntimeAdmission.fs" />
    <Compile Include="ManagedCopySignerApprovalRead.fs" />
    <Compile Include="ManagedCopySignerApprovalHolder.fs" />
    <Compile Include="ManagedCopySignerApproval.fs" />
    <Compile Include="ManagedCopySignerWrite.fs" />
    <Compile Include="ManagedCopyExports.fs" />
    <Compile Include="RecoveryArtifactExportCommit.fs" />
    <Compile Include="CaseLifecycleCandidate.fs" />
    <Compile Include="PreparationData.fs" />
    <Compile Include="RecoveryStoreQueries.fs" />
    <Compile Include="OperationAuthorityStore.fs" />
    <Compile Include="PreparationPageStore.fs" />
    <Compile Include="PreparationLifecycleStore.fs" />
    <Compile Include="SubmissionAttemptStore.fs" />
    <Compile Include="Rows.fs" />
    <Compile Include="ActorGrantWrite.fs" />
    <Compile Include="ActorGrantOwnerSafety.fs" />
    <Compile Include="ActorGrantRegistryQueries.fs" />
    <Compile Include="ActorRegistrationWrite.fs" />
    <Compile Include="ActorGrantRegistry.fs" />
    <Compile Include="ActorManagementGrant.fs" />
    <Compile Include="ActorManagementStore.fs" />
    <Compile Include="ActorGrantDeployment.fs" />
    <Compile Include="CaseLifecycleAuditRows.fs" />
    <Compile Include="CaseLifecycleAuditRelations.fs" />
    <Compile Include="CaseLifecycleAuditCodec.fs" />
    <Compile Include="CaseLifecycleAuditEvidence.fs" />
    <Compile Include="CaseLifecycleAuditReplay.fs" />
    <Compile Include="CaseLifecycleAuditCursor.fs" />
    <Compile Include="CaseLifecycleAuditEventCheck.fs" />
    <Compile Include="CaseLifecycleAuditScan.fs" />
    <Compile Include="CaseLifecycleAudit.fs" />
    <Compile Include="DataAuditCommon.fs" />
    <Compile Include="DataAuditAcceptedRows.fs" />
    <Compile Include="DataAuditDispositionCursor.fs" />
    <Compile Include="DataAuditReplay.fs" />
    <Compile Include="DataAuditCaseReplay.fs" />
    <Compile Include="DataAuditTechnical.fs" />
    <Compile Include="DataAuditExportBudgets.fs" />
    <Compile Include="DataAuditExportIntegrity.fs" />
    <Compile Include="DataAuditExportSql.fs" />
    <Compile Include="DataAuditExportCandidates.fs" />
    <Compile Include="DataAuditSignerApprovals.fs" />
    <Compile Include="DataAuditSignerRows.fs" />
    <Compile Include="DataAuditSignerEvents.fs" />
    <Compile Include="CaseTombstonePrunePrimaryRead.fs" />
    <Compile Include="CaseWitnessAuditEvidence.fs" />
    <Compile Include="DataAuditAuthorityRows.fs" />
    <Compile Include="DataAuditWitness.fs" />
    <Compile Include="DataAuditJournalPruned.fs" />
    <Compile Include="DataAuditJournalAbort.fs" />
    <Compile Include="DataAuditJournalTechnical.fs" />
    <Compile Include="DataAuditJournalExternalPublication.fs" />
    <Compile Include="DataAuditJournalQueries.fs" />
    <Compile Include="DataAuditJournalCommands.fs" />
    <Compile Include="DataAuditInstallationLossWitness.fs" />
    <Compile Include="DataAuditInstallationLossPrimary.fs" />
    <Compile Include="DataAuditInstallationLoss.fs" />
    <Compile Include="DataAuditJournal.fs" />
    <Compile Include="DataAuditAuthorityProjection.fs" />
    <Compile Include="InstallationLossRetirementSigners.fs" />
    <Compile Include="CaseErasureDenials.fs" />
    <Compile Include="CaseErasureWitnessDenials.fs" />
    <Compile Include="CaseErasurePurgedDenialsAudit.fs" />
    <Compile Include="CaseErasurePurgeDelete.fs" />
    <Compile Include="CaseErasurePurgePort.fs" />
    <Compile Include="CaseErasurePurgeCandidate.fs" />
    <Compile Include="DataAuditErasure.fs" />
    <Compile Include="DataAuditPurgedErasureRows.fs" />
    <Compile Include="DataAuditPurgedApprovals.fs" />
    <Compile Include="DataAuditPurgedErasureCandidate.fs" />
    <Compile Include="StoreData.fs" />
    <Compile Include="AcceptedCasePersistence.fs" />
    <Compile Include="CaseReadLifecycleEvidence.fs" />
    <Compile Include="CaseReadEvidence.fs" />
    <Compile Include="ActorReadStore.fs" />
    <Compile Include="ActorOperationReadStore.fs" />
    <Compile Include="ActorMutationSuppression.fs" />
    <Compile Include="ActorMutationGuard.fs" />
    <Compile Include="RecoveryArtifactImportProof.fs" />
    <Compile Include="RecoveryArtifactExportAdmission.fs" />
    <Compile Include="RecoveryArtifactExportIssue.fs" />
    <Compile Include="CaseLifecycleRead.fs" />
    <Compile Include="CaseErasurePurgeApprovalRead.fs" />
    <Compile Include="CaseErasurePurgeWrite.fs" />
    <Compile Include="CaseErasurePurgeRead.fs" />
    <Compile Include="CaseLifecyclePaymentEvidence.fs" />
    <Compile Include="CaseErasureFenceWrite.fs" />
    <Compile Include="CaseLifecycleWrite.fs" />
    <Compile Include="CaseLifecycleApprovalWrite.fs" />
    <Compile Include="CaseLifecycleStoreSupport.fs" />
    <Compile Include="CaseErasureRequestProof.fs" />
    <Compile Include="CaseLifecycleApplyDecision.fs" />
    <Compile Include="CaseLifecycleApplyCommit.fs" />
    <Compile Include="CaseLifecycleApply.fs" />
    <Compile Include="CaseLifecycleApproveDecision.fs" />
    <Compile Include="CaseLifecycleApproveCommit.fs" />
    <Compile Include="CaseLifecycleApprove.fs" />
    <Compile Include="CaseLifecycleReview.fs" />
    <Compile Include="CaseLifecycleStore.fs" />
    <Compile Include="RecoveryReadAuthority.fs" />
    <Compile Include="RecoveryReadStore.fs" />
    <Compile Include="RecoveryAcceptedObservation.fs" />
    <Compile Include="RecoveryRetentionStore.fs" />
    <Compile Include="RecoveryStartStore.fs" />
    <Compile Include="RecoveryDismissalStore.fs" />
    <Compile Include="RecoveryExecutionSupport.fs" />
    <Compile Include="RecoveryExecutionOutcomes.fs" />
    <Compile Include="RecoveryExecutionDecision.fs" />
    <Compile Include="RecoveryExecutionStore.fs" />
    <Compile Include="RecoveryStore.fs" />
    <Compile Include="Store.fs" />
    <Compile Include="AdministrationExecution.fs" />
    <Compile Include="OwnerConnection.fs" />
    <Compile Include="CaseLifecycleReconcile.fs" />
    <Compile Include="ActorGrantAdministration.fs" />
    <Compile Include="InstallationBusinessZone.fs" />
    <Compile Include="SchemaBaseline.fs" />
    <Compile Include="ManagedCopySignerCommit.fs" />
    <Compile Include="ManagedCopySignerPolicy.fs" />
    <Compile Include="ManagedCopyDeletionApprovalCandidate.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalCandidate.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalCodec.fs" />
    <Compile Include="WriterHandoffApprovalCandidate.fs" />
    <Compile Include="WriterHandoffApproval.fs" />
    <Compile Include="WriterHandoffEvidenceHash.fs" />
    <Compile Include="DataAuditHandoffOwnerRole.fs" />
    <Compile Include="DataAuditCopyAdoptionOwnerRole.fs" />
    <Compile Include="DataAuditCopyAdoptionSignerRole.fs" />
    <Compile Include="DataAuditExternalPublicationHolder.fs" />
    <Compile Include="DataAuditWriterHandoffApprovals.fs" />
    <Compile Include="DataAuditWriterHandoffRows.fs" />
    <Compile Include="DataAuditWriterHandoffEvidence.fs" />
    <Compile Include="DataAuditWriterHandoffs.fs" />
    <Compile Include="ManagedCopySignerAdministrationCore.fs" />
    <Compile Include="ManagedCopyEvidenceTypes.fs" />
    <Compile Include="ManagedCopyPhysicalProofTypes.fs" />
    <Compile Include="ManagedCopyAdoptionPort.fs" />
    <Compile Include="ManagedCopyExternalPublicationPort.fs" />
    <Compile Include="ManagedCopyAbsenceEvidence.fs" />
    <Compile Include="ManagedCopyRegistrationAttestation.fs" />
    <Compile Include="ManagedCopyPhysicalProof.fs" />
    <Compile Include="ManagedCopyAdoptionDocumentCommon.fs" />
    <Compile Include="ManagedCopyExternalPublicationDocuments.fs" />
    <Compile Include="ManagedCopyExternalPublicationCandidate.fs" />
    <Compile Include="ManagedCopyExternalPublicationCodec.fs" />
    <Compile Include="ManagedCopyExternalPublicationRead.fs" />
    <Compile Include="ManagedCopyAdoptionCustody.fs" />
    <Compile Include="ManagedCopyAdoptionLocationReceipts.fs" />
    <Compile Include="ManagedCopyAdoptionSignatureEvidence.fs" />
    <Compile Include="ManagedCopyExternalPublicationChecks.fs" />
    <Compile Include="ManagedCopyExternalPublicationCaseLink.fs" />
    <Compile Include="ManagedCopyExternalPublicationEvidence.fs" />
    <Compile Include="ManagedCopyExternalPublicationOrigin.fs" />
    <Compile Include="ManagedCopyAdoptionOriginProof.fs" />
    <Compile Include="DataAuditExternalPublications.fs" />
    <Compile Include="ManagedCopyExternalPublicationWrite.fs" />
    <Compile Include="ManagedCopyAdoptionDocumentPolicy.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerRead.fs" />
    <Compile Include="ManagedCopyAdoptionEvidenceRows.fs" />
    <Compile Include="ManagedCopyAdoptionEventEvidence.fs" />
    <Compile Include="WriterHandoffCanonical.fs" />
    <Compile Include="WriterHandoffPreparation.fs" />
    <Compile Include="WriterHandoffSettlement.fs" />
    <Compile Include="WriterHandoffAbort.fs" />
    <Compile Include="WriterHandoffQualificationPort.fs" />
    <Compile Include="WriterActivationPort.fs" />
    <Compile Include="WriterActivationCandidate.fs" />
    <Compile Include="WriterHandoffCutoff.fs" />
    <Compile Include="WriterHandoffOwnerChecks.fs" />
    <Compile Include="WriterActivationEvidenceChecks.fs" />
    <Compile Include="WriterActivationWitness.fs" />
    <Compile Include="InstallationUseActivationCandidate.fs" />
    <Compile Include="InstallationUseActivationCodec.fs" />
    <Compile Include="RealDataActivationOwnerPolicy.fs" />
    <Compile Include="InstallationUsePlanCodec.fs" />
    <Compile Include="InstallationUsePlanRead.fs" />
    <Compile Include="RealDataActivationApprovalCandidate.fs" />
    <Compile Include="RealDataActivationApprovalRows.fs" />
    <Compile Include="RealDataActivationApprovalRecovery.fs" />
    <Compile Include="RealDataActivationApprovalChecks.fs" />
    <Compile Include="RealDataActivationPlanReview.fs" />
    <Compile Include="RealDataActivationApproval.fs" />
    <Compile Include="InstallationUseActivationWitness.fs" />
    <Compile Include="InstallationUseActivationPrimary.fs" />
    <Compile Include="InstallationUseApprovalChain.fs" />
    <Compile Include="InstallationUseActivationApprovals.fs" />
    <Compile Include="DataAuditInstallationUseApprovals.fs" />
    <Compile Include="InstallationUsePlanPublisher.fs" />
    <Compile Include="InstallationUseActivationPreflight.fs" />
    <Compile Include="InstallationUseActivationCommit.fs" />
    <Compile Include="InstallationUseActivationOwner.fs" />
    <Compile Include="InstallationUseActivationReconcile.fs" />
    <Compile Include="DataAuditInstallationUse.fs" />
    <Compile Include="WriterActivationPrimary.fs" />
    <Compile Include="WriterActivationRead.fs" />
    <Compile Include="DataAuditWriterActivationRows.fs" />
    <Compile Include="DataAuditWriterActivationEvidence.fs" />
    <Compile Include="DataAuditWriterActivations.fs" />
    <Compile Include="WriterHandoffOwnerWrite.fs" />
    <Compile Include="WriterHandoffOwnerRead.fs" />
    <Compile Include="WriterHandoffOwnerReconcile.fs" />
    <Compile Include="WriterHandoffWitnessCommands.fs" />
    <Compile Include="WriterHandoffWitnessAbortCommands.fs" />
    <Compile Include="WriterHandoffAbortApproval.fs" />
    <Compile Include="WriterHandoffOwnerAbortGrantEvidence.fs" />
    <Compile Include="WriterHandoffOwnerAbortEvidence.fs" />
    <Compile Include="DataAuditWriterHandoffAborts.fs" />
    <Compile Include="DataAuditWriterHandoffPreparationRows.fs" />
    <Compile Include="DataAuditWriterHandoffPreparations.fs" />
    <Compile Include="ManagedCopyTransitionAttestation.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionAttestation.fs" />
    <Compile Include="ManagedCopyDeletionEvidenceRead.fs" />
    <Compile Include="CaseWitnessPayloadClassifier.fs" />
    <Compile Include="CaseWitnessPayloadTargets.fs" />
    <Compile Include="CaseTombstoneCandidate.fs" />
    <Compile Include="CaseTombstoneTerminalCandidate.fs" />
    <Compile Include="CaseTombstoneTerminalProposalCodec.fs" />
    <Compile Include="CaseTombstoneProposalCodec.fs" />
    <Compile Include="CaseTombstonePruneExecutionCandidate.fs" />
    <Compile Include="CaseTombstonePrunePort.fs" />
    <Compile Include="CaseWitnessPayloadPrune.fs" />
    <Compile Include="CaseTombstoneRead.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalPolicy.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalSigners.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalRead.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalPersistence.fs" />
    <Compile Include="CaseTombstoneTerminalRead.fs" />
    <Compile Include="CaseTombstoneHoldReplay.fs" />
    <Compile Include="CaseTombstoneHoldPersistence.fs" />
    <Compile Include="CaseTombstonePruneApprovalRead.fs" />
    <Compile Include="CaseTombstonePruneApprovalPolicy.fs" />
    <Compile Include="CaseTombstoneTerminalPolicy.fs" />
    <Compile Include="CaseTombstoneTerminalPort.fs" />
    <Compile Include="CaseTombstoneTerminalEventCandidate.fs" />
    <Compile Include="CaseTombstoneTerminalEventCodec.fs" />
    <Compile Include="CaseTombstonePruneOwnerApprovals.fs" />
    <Compile Include="CaseTombstonePrunePrimaryWrite.fs" />
    <Compile Include="CaseTombstonePruneOwnerChecks.fs" />
    <Compile Include="CaseTombstonePruneTargetRows.fs" />
    <Compile Include="CaseTombstonePruneTargetAudit.fs" />
    <Compile Include="CaseTombstonePrunePostcutoffAudit.fs" />
    <Compile Include="CaseTombstonePruneReceiptAudit.fs" />
    <Compile Include="CaseTombstoneHoldWrite.fs" />
    <Compile Include="CaseTombstoneReview.fs" />
    <Compile Include="CaseTombstonePruneOwnerCommit.fs" />
    <Compile Include="CaseTombstonePruneApprovalPersistence.fs" />
    <Compile Include="CaseTombstonePruneApprovalWrite.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalPersistence.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalSet.fs" />
    <Compile Include="CaseTombstoneTerminalOwnerApprovals.fs" />
    <Compile Include="CaseTombstoneTerminalOwnerPrepare.fs" />
    <Compile Include="CaseTombstoneTerminalEventWrite.fs" />
    <Compile Include="CaseTombstoneTerminalEventRead.fs" />
    <Compile Include="CaseTombstoneTerminalOwnerCommit.fs" />
    <Compile Include="DataAuditTerminalStewardRole.fs" />
    <Compile Include="CaseTombstoneTerminalEventProof.fs" />
    <Compile Include="CaseTombstoneTerminalEventAudit.fs" />
    <Compile Include="CaseTombstoneTerminalProjectionAudit.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalWrite.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalWrite.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerApproval.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerCandidate.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerCodec.fs" />
    <Compile Include="ManagedCopyAdoptionAuthorityTip.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerProjectionWrite.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerReceiptWrite.fs" />
    <Compile Include="ManagedCopyAdoptionEvidenceAuthority.fs" />
    <Compile Include="ManagedCopyAdoptionEvidence.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionPolicy.fs" />
    <Compile Include="DataAuditAdoptedCopyRows.fs" />
    <Compile Include="DataAuditAdoptedCopyTransitions.fs" />
    <Compile Include="ManagedCopyDeletionApprovalPolicy.fs" />
    <Compile Include="ManagedCopyDeletionApprovalTarget.fs" />
    <Compile Include="ManagedCopyDeletionApprovalExecution.fs" />
    <Compile Include="DataAuditCopyAdoptions.fs" />
    <Compile Include="DataAuditProductExportEventChain.fs" />
    <Compile Include="DataAuditExportWitness.fs" />
    <Compile Include="DataAuditManagedCopies.fs" />
    <Compile Include="CaseTombstoneHoldAuditRows.fs" />
    <Compile Include="CaseTombstoneHoldAudit.fs" />
    <Compile Include="CaseTombstonePruneApprovalAuditRows.fs" />
    <Compile Include="CaseTombstonePruneApprovalAudit.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalAuditRows.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalAudit.fs" />
    <Compile Include="DataAuditPurgedErasure.fs" />
    <Compile Include="DataAuditTerminalEvents.fs" />
    <Compile Include="DataAuditErasureFences.fs" />
    <Compile Include="CaseTombstoneStore.fs" />
    <Compile Include="ManagedCopyOwnerWrite.fs" />
    <Compile Include="ManagedCopyOwnerRead.fs" />
    <Compile Include="ManagedCopyPhysicalVerificationPort.fs" />
    <Compile Include="ManagedCopyTransitionPolicy.fs" />
    <Compile Include="ManagedCopyAdministration.fs" />
    <Compile Include="ManagedCopyTransitionAdministration.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerChecks.fs" />
    <Compile Include="ManagedCopyPhysicalVerificationPolicy.fs" />
    <Compile Include="ManagedCopyVerifiedRestoreWrite.fs" />
    <Compile Include="ManagedCopyVerifiedRestore.fs" />
    <Compile Include="ManagedCopyVerifiedDeletionWrite.fs" />
    <Compile Include="ManagedCopyVerifiedDeletion.fs" />
    <Compile Include="ManagedCopyVerifiedDeletionExecution.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionRead.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionWrite.fs" />
    <Compile Include="ManagedCopyAdoptedDeletionEvidence.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionChecks.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionAdministration.fs" />
    <Compile Include="DataAuditOwnerCopyWitnessProof.fs" />
    <Compile Include="DataAuditOwnerCopyTransitions.fs" />
    <Compile Include="DataAuditCopyPhysicalVerifierRole.fs" />
    <Compile Include="DataAuditCopyPhysicalRows.fs" />
    <Compile Include="DataAuditCopyPhysicalVerifications.fs" />
    <Compile Include="ManagedCopyOwnerInspection.fs" />
    <Compile Include="DataAuditOwnerCopies.fs" />
    <Compile Include="DataAuditCopyDeletionApprovals.fs" />
    <Compile Include="DataAuditCopyAdoptionApprovalRows.fs" />
    <Compile Include="DataAuditCopyAdoptionApprovals.fs" />
    <Compile Include="DataAuditCustody.fs" />
    <Compile Include="DataAuditSummary.fs" />
    <Compile Include="DataAuditAuthority.fs" />
    <Compile Include="DataAudit.fs" />
    <Compile Include="ManagedCopyExternalPublicationOwner.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerCommit.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerReplay.fs" />
    <Compile Include="ManagedCopyAdoptionOwner.fs" />
    <Compile Include="CaseTombstoneTerminalOwnerReplay.fs" />
    <Compile Include="CaseTombstoneTerminalOwner.fs" />
    <Compile Include="WriterHandoffOwnerPreparation.fs" />
    <Compile Include="WriterHandoffOwnerSettlementChecks.fs" />
    <Compile Include="WriterHandoffOwnerSettlementCompletion.fs" />
    <Compile Include="WriterHandoffOwnerSettlement.fs" />
    <Compile Include="WriterHandoffActivation.fs" />
    <Compile Include="WriterHandoffOwnerAbortStage.fs" />
    <Compile Include="WriterHandoffOwnerAbortDraft.fs" />
    <Compile Include="WriterHandoffOwnerAbortWrite.fs" />
    <Compile Include="WriterHandoffOwnerAbortBackfill.fs" />
    <Compile Include="WriterHandoffOwnerAbortRelease.fs" />
    <Compile Include="InstallationLossRetirementState.fs" />
    <Compile Include="InstallationLossRetirementDraft.fs" />
    <Compile Include="InstallationLossRetirementPreflight.fs" />
    <Compile Include="InstallationLossRetirementCommit.fs" />
    <Compile Include="InstallationLossRetirementAdministration.fs" />
    <Compile Include="CaseTombstonePruneOwner.fs" />
    <Compile Include="CaseErasurePurgePreparation.fs" />
    <Compile Include="CaseErasurePurgeCommit.fs" />
    <Compile Include="CaseErasurePurgeExecution.fs" />
    <Compile Include="PreparationPruning.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ClaimCore.Domain/ClaimCore.Domain.fsproj" />
    <ProjectReference Include="../ClaimCore.Application/ClaimCore.Application.fsproj" />
    <ProjectReference Include="../ClaimCore.RecordFormat/ClaimCore.RecordFormat.fsproj" />
    <ProjectReference Include="../ClaimCore.Witness/ClaimCore.Witness.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" PrivateAssets="compile;build;buildTransitive;analyzers;contentFiles" />
    <PackageReference Include="NSec.Cryptography" PrivateAssets="compile;build;buildTransitive;analyzers;contentFiles" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../db/baseline.sql" LogicalName="ClaimCore.SchemaBaseline.sql" />
    <EmbeddedResource Include="../../db/schema-baseline.json" LogicalName="ClaimCore.SchemaBaseline.json" />
    <EmbeddedResource Include="../../db/catalog-manifest.sql" LogicalName="ClaimCore.CatalogManifest.sql" />
    <EmbeddedResource Include="../../db/catalog-manifest.pg18.6.json" LogicalName="ClaimCore.CatalogManifest.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../db/postgresql-baseline.json" LogicalName="ClaimCore.PostgresBaseline.json" />
  </ItemGroup>
</Project>
