/** Generated endpoint-owned types exposed by the validated browser API boundary. */
export type {
  AdvisoryReview,
  ApiResult,
  CaseFields,
  CaseSummary,
  CaseView,
  CommandDescriptor,
  CommandDraft,
  CommandInputDescriptor,
  CommandInputShape,
  CorrectionGroupDescriptor,
  CurrentCase,
  DefinitionPayload,
  EndpointOutcome,
  FieldDescriptor,
  PreparationDetails,
  PreparationSummary,
  Receipt,
  Rejection,
  RecoveryDetails,
  RecoveryImportPreview,
  RecoveryInspection,
  RecoveryListItem,
  RecoveryPage,
  RevokedOperation,
  SemanticDefinition,
  SessionSnapshot,
  WebV2Response,
} from "../generated/convergence/web-v2.types";
