namespace ClaimCore.Database

/// Exact owner-command names published by the administration response contract.
module internal DatabaseCommandCatalogue =
    let values =
        [
            "INITIALIZE"
            "INITIALIZE_REAL_DATA"
            "PUBLISH_REAL_DATA_ACTIVATION_PLAN"
            "ACTIVATE_REAL_DATA"
            "RECONCILE_REAL_DATA_ACTIVATION"
            "INITIALIZE_WITNESS"
            "PROVISION_INITIAL_OWNER"
            "VERIFY"
            "VERIFY_DATA"
            "HOLD_BACKUP_CAPTURE"
            "RECONCILE_BACKUP_CAPTURE"
            "ISSUE_BACKUP_HEALTH"
            "RECONCILE_BACKUP_HEALTH"
            "PRUNE"
            "REGISTER_COPY_SIGNER"
            "RETIRE_COPY_SIGNER"
            "INGEST_MANAGED_COPY"
            "TRANSITION_MANAGED_COPY"
            "VERIFY_DELETE_MANAGED_COPY"
            "VERIFY_MANAGED_COPY"
            "ADOPT_MANAGED_COPY"
            "PUBLISH_EXTERNAL_COPY"
            "TRANSITION_ADOPTED_COPY"
            "VERIFY_DELETE_ADOPTED_COPY"
            "CERTIFY_MANAGED_PAYLOAD_ABSENCE"
            "COMPLETE_SUPPRESSION_HORIZON"
            "PREPARE_WRITER_HANDOFF"
            "SETTLE_WRITER_HANDOFF"
            "ACTIVATE_WRITER_HANDOFF"
            "ABORT_WRITER_HANDOFF"
            "DRAFT_WRITER_HANDOFF_ABORT"
            "PURGE_LIVE"
            "PRUNE_WITNESS_PAYLOAD"
            "INSPECT_MANAGED_COPY"
            "RECONCILE_LIFECYCLE_EVENT"
            "VERIFY_RESTORE_REPORT"
            "VERIFY_FENCED_TAIL"
        ]
