import { renderedTokens, validateTokens } from "./localization-tokens.mjs";
import { format, resolveConfig } from "prettier";
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import {
  addDomain,
  diagnosticRequirements,
  messageShape,
  pseudolocalize,
  readCatalog,
  validateCatalog,
  validateCoverage,
} from "./localization-policy.mjs";

const root = resolve(import.meta.dirname, "..");
const input = resolve(root, "src/presentation/catalogs");
const output = resolve(root, "src/presentation/generated");
const generate = process.argv.slice(2).includes("--write");
const languages = ["en", "lv", "ar"];
const catalogs = {};
const domains = ["ui", "notice", "token", "field", "command", "group", "diagnostic"];
const expectedInputs = languages
  .flatMap((language) => domains.map((domain) => `${language}.${domain}.json`))
  .sort();
if (JSON.stringify((await readdir(input)).sort()) !== JSON.stringify(expectedInputs))
  throw new Error("Unexpected or missing localization catalog domain.");
for (const lang of languages) {
  const catalog = {};
  const files = (await readdir(input))
    .filter((f) => f.startsWith(`${lang}.`) && f.endsWith(".json"))
    .sort();
  for (const file of files) {
    const entries = readCatalog(await readFile(resolve(input, file), "utf8"));
    addDomain(catalog, entries, file.slice(lang.length + 1, -5));
  }
  catalogs[lang] = catalog;
}
for (const lang of languages) validateCatalog(catalogs.en, catalogs[lang], lang);
const generated = resolve(root, "src/generated/convergence");
const semantic = JSON.parse(
  await readFile(resolve(generated, "semantic-core-v1.contract.json"), "utf8"),
);
const host = JSON.parse(
  await readFile(resolve(generated, "web-v2.host-failure.schema.json"), "utf8"),
);
const requirements = diagnosticRequirements(semantic, host);
validateCoverage(catalogs.en, semantic, requirements);
const recoveryTypes = await readFile(resolve(generated, "web-v2.types.recovery.ts"), "utf8");
validateTokens(catalogs.en, renderedTokens(semantic, recoveryTypes));
await mkdir(output, { recursive: true });
const expected = {};
const args = {};
for (const [lang, catalog] of Object.entries(catalogs)) {
  const compiled = {};
  for (const [key, message] of Object.entries(catalog)) {
    const shape = messageShape(message, lang);
    compiled[key] = shape.ast;
    if (lang === "en") args[key] = shape.args;
  }
  expected[`${lang}.json`] = JSON.stringify(compiled) + "\n";
}
const pseudo = Object.fromEntries(
  Object.entries(JSON.parse(expected["en.json"])).map(([k, ast]) => [
    k,
    [{ type: 0, value: "⟦" }, ...pseudolocalize(ast), { type: 0, value: "⟧" }],
  ]),
);
expected["en-XA.json"] = JSON.stringify(pseudo) + "\n";
expected["diagnostic-parameters.json"] = JSON.stringify(requirements, null, 2) + "\n";
for (const domain of domains) {
  const entries = Object.entries(args).filter(([k]) => k.startsWith(`${domain}.`));
  expected[`args.${domain}.ts`] =
    "/* Generated by localization.mjs; do not edit. */\n" +
    `export type ${domain[0].toUpperCase() + domain.slice(1)}Args = {\n` +
    entries
      .map(
        ([k, shape]) =>
          `  ${JSON.stringify(k)}: ${
            Object.keys(shape).length === 0
              ? "Readonly<Record<string, never>>"
              : `{${Object.entries(shape)
                  .map(([name, role]) => ` readonly ${JSON.stringify(name)}: ${role}`)
                  .join(";")}}`
          };`,
      )
      .join("\n") +
    "\n};\n";
}
expected["arguments.json"] = JSON.stringify(args) + "\n";
const prettierOptions = await resolveConfig(resolve(root, "package.json"));
for (const [file, raw] of Object.entries(expected)) {
  const text = await format(raw, { ...prettierOptions, filepath: file });
  const path = resolve(output, file);
  if (generate) await writeFile(path, text);
  else if ((await readFile(path, "utf8").catch(() => null)) !== text)
    throw new Error(`Localization generated file drift: ${file}`);
}
const extras = (await readdir(output)).filter((f) => !Object.hasOwn(expected, f));
if (extras.length) throw new Error("Unexpected generated localization file.");
process.stdout.write(
  `Localization validated: ${Object.keys(args).length} keys, ${Object.keys(requirements).length} diagnostic identities, three real languages and one pseudolocale.\n`,
);
