// Third-party notices for a published .NET product, generated from its CycloneDX SBOM. Every
// third-party component must declare exactly one reviewed redistribution license; components are
// grouped under the license text they must carry.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compareOrdinal } from "../suites/inventory.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const architecture = /** @type {{ components: { name: string, tier: string }[] }} */ (
  JSON.parse(readFileSync(resolve(here, "../../../config/architecture.json"), "utf8"))
);
export const productComponentNames = new Set(
  architecture.components.filter(({ tier }) => tier === "product").map(({ name }) => name),
);
const reviewedLicenses = new Set(["MIT", "PostgreSQL", "ISC"]);
const separator = `\n\n${"-".repeat(80)}\n\n`;

/**
 * @typedef {object} Component
 * @property {string} [name]
 * @property {string} [version]
 * @property {string} [copyright]
 * @property {{ license?: { id?: string } }[]} [licenses]
 * @property {{ type?: string, url?: string }[]} [externalReferences]
 */

/**
 * @param {Component} component
 * @returns {string} The one reviewed license id the component declares.
 */
function declaredLicense({ name = "", licenses = [] }) {
  const [only] = licenses.map((entry) => entry.license?.id);
  if (licenses.length !== 1 || only === undefined || only.trim() === "") {
    throw new Error(`${name} lacks one exact redistribution license.`);
  }
  if (!reviewedLicenses.has(only)) {
    throw new Error(`${name} uses an unreviewed .NET redistribution license.`);
  }
  if (only === "ISC" && name !== "libsodium") {
    throw new Error("Unreviewed ISC package identity.");
  }
  return only;
}

/**
 * @param {unknown} sbom A parsed CycloneDX document.
 * @returns {Component[]} The third-party components in a stable order.
 */
function thirdParty(sbom) {
  const all = /** @type {{ components?: Component[] }} */ (sbom).components ?? [];
  const components = all
    .filter((component) => !productComponentNames.has(component.name ?? ""))
    .sort(
      (left, right) =>
        compareOrdinal(left.name ?? "", right.name ?? "") ||
        compareOrdinal(left.version ?? "", right.version ?? ""),
    );
  if (components.length === 0) {
    throw new Error("The .NET SBOM has no third-party components.");
  }
  return components;
}

/**
 * @param {Component} component
 * @returns {{ license: string, entry: string }} The license it declares and its notice entry.
 */
function describe(component) {
  const { name = "", version = "", copyright = "" } = component;
  if (name.trim() === "" || version.trim() === "") {
    throw new Error("A .NET SBOM component lacks identity.");
  }
  if (copyright.trim() === "") {
    throw new Error("A .NET SBOM component lacks copyright attribution.");
  }
  const license = declaredLicense(component);
  const upstream =
    (component.externalReferences ?? []).find(
      (reference) => reference.type === "website" || reference.type === "vcs",
    )?.url ?? "Not supplied";
  return {
    license,
    entry: `Package: ${name}@${version}\nDeclared license: ${license}\nCopyright: ${copyright}\nUpstream: ${upstream}`,
  };
}

/**
 * @param {unknown} sbom A parsed CycloneDX document.
 * @param {(component: Component) => string} readPackageNotice
 * @returns {string} The notices file's contents.
 */
export function renderNotices(sbom, readPackageNotice) {
  /** @type {Map<string, string[]>} */
  const groups = new Map();
  for (const component of thirdParty(sbom)) {
    const { entry } = describe(component);
    const text = readPackageNotice(component).trim();
    if (text === "") {
      throw new Error("Package redistribution material is empty.");
    }
    groups.set(text, [...(groups.get(text) ?? []), entry]);
  }
  const sections = [...groups].map(([text, entries]) => `${entries.join("\n\n")}\n\n${text}`);
  const header = [
    "ClaimCore .NET \u2014 third-party notices",
    "",
    "Generated from the locked production dependency graph. Do not edit this file manually.",
    "ClaimCore licensing and source availability are described separately in LICENSE.",
    "",
  ].join("\n");
  return `${header}\n${sections.join(separator)}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [sbomPath, assetsPath, outputPath] = process.argv.slice(2);
  if (sbomPath === undefined || assetsPath === undefined || outputPath === undefined) {
    process.stderr.write("usage: notices.mjs <sbom.cdx.json> <project.assets.json> <output>\n");
    process.exit(2);
  }
  const { packageNoticeReader } = await import("./nuget-notices.mjs");
  writeFileSync(
    outputPath,
    renderNotices(JSON.parse(readFileSync(sbomPath, "utf8")), packageNoticeReader(assetsPath)),
  );
}
