<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../BoundedProcess.fs" Link="BoundedProcess.fs" />
    <Compile Include="../RepositoryRoot.fs" Link="RepositoryRoot.fs" />
    <Compile Include="../CommandExecution.fs" Link="CommandExecution.fs" />
    <Compile Include="FixtureEnvironment.fs" />
    <Compile Include="FixturePrivateFiles.fs" />
    <Compile Include="FixtureWitnessIdentity.fs" />
    <Compile Include="FixtureWitnessDatabase.fs" />
    <Compile Include="FixtureDatabase.fs" />
    <Compile Include="CaseListCursorTestSupport.fs" />
    <Compile Include="CaseListCursorProtectionTests.fs" />
    <Compile Include="FixtureCommandExecution.fs" />
    <Compile Include="ActorBoundStoreFixture.fs" />
    <Compile Include="Fixtures.fs" />
    <Compile Include="TransactionPaginationTests.fs" />
    <Compile Include="TransactionRejectionTests.fs" />
    <Compile Include="OperationLookupTests.fs" />
    <Compile Include="TransactionReplayTests.fs" />
    <Compile Include="TransactionTests.fs" />
    <Compile Include="SchemaTests.fs" />
    <Compile Include="FieldStorageTests.fs" />
    <Compile Include="CoreRuntimeLifecycleTests.fs" />
    <Compile Include="CoreBoundaryTests.fs" />
    <Compile Include="RuntimeLifecycleTests.fs" />
    <Compile Include="RuntimeResourceCleanupTests.fs" />
    <Compile Include="RuntimeConstructionTests.fs" />
    <Compile Include="CliInterruptionProcessTests.fs" />
    <Compile Include="StorageDateTests.fs" />
    <Compile Include="DomainEvidenceTests.fs" />
    <Compile Include="CatalogAdmissionTests.fs" />
    <Compile Include="CatalogEpochChanges.fs" />
    <Compile Include="CatalogEpochTokenTests.fs" />
    <Compile Include="CatalogEpochTests.fs" />
    <Compile Include="StorageBoundaryTests.fs" />
    <Compile Include="PreparationTests.fs" />
    <Compile Include="AcceptedReplayStorageTests.fs" />
    <Compile Include="AcceptedHistoryRetentionTests.fs" />
    <Compile Include="WitnessProtocolTests.fs" />
    <Compile Include="WitnessKeyCustodyTests.fs" />
    <Compile Include="RecoveryArtifactKeyCustodyTests.fs" />
    <Compile Include="PreparationBoundaryTests.fs" />
    <Compile Include="FreshBaselineSupport.fs" />
    <Compile Include="FixtureWitnessWriterStore.fs" />
    <Compile Include="ActorGrantTestSupport.fs" />
    <Compile Include="RuntimeAuditCadenceTests.fs" />
    <Compile Include="RuntimeSchedulingTests.fs" />
    <Compile Include="WitnessAuditorTests.fs" />
    <Compile Include="RecoveryArtifactExportTestSupport.fs" />
    <Compile Include="RecoveryArtifactExportTests.fs" />
    <Compile Include="RecoveryArtifactImportTests.fs" />
    <Compile Include="RecoveryArtifactImportPreviewTests.fs" />
    <Compile Include="TechnicalWitnessTestSupport.fs" />
    <Compile Include="RecoverySnapshotGate.fs" />
    <Compile Include="RecoverySnapshotTests.fs" />
    <Compile Include="AcceptedReplayWitnessTests.fs" />
    <Compile Include="AuthorityOperationFenceCloseTests.fs" />
    <Compile Include="RevocationIntentIdentityTests.fs" />
    <Compile Include="SettledAttemptExecutionTests.fs" />
    <Compile Include="AuthorityOperationFenceFixture.fs" />
    <Compile Include="AuthorityOperationFenceTests.fs" />
    <Compile Include="WitnessedCapacityTests.fs" />
    <Compile Include="TechnicalWitnessPruneTests.fs" />
    <Compile Include="TechnicalWitnessTests.fs" />
    <Compile Include="DataAuditTests.fs" />
    <Compile Include="DatabaseVerifyDataTests.fs" />
    <Compile Include="RestoreReportOwnerRosterTests.fs" />
    <Compile Include="RestoreReportPairBindingTests.fs" />
    <Compile Include="RestorePublicationTests.fs" />
    <Compile Include="RestoreProduceCanonicalTests.fs" />
    <Compile Include="RestoreReportScopeTests.fs" />
    <Compile Include="RestoreProduceOutputTests.fs" />
    <Compile Include="RestoreProduceArchiveTests.fs" />
    <Compile Include="RestoreProduceBarrierTests.fs" />
    <Compile Include="RestoreProduceWalCoverageTests.fs" />
    <Compile Include="RestoreFencedTailTests.fs" />
    <Compile Include="RestoreProduceAuditTests.fs" />
    <Compile Include="RestorePhysicalProcess.fs" />
    <Compile Include="RestorePhysicalWalRange.fs" />
    <Compile Include="RestorePhysicalArchiveEvidence.fs" />
    <Compile Include="RestoreRegisteredWalCapture.fs" />
    <Compile Include="RestorePhysicalConnections.fs" />
    <Compile Include="RestorePhysicalIdentityChecks.fs" />
    <Compile Include="RestorePhysicalCopyFixture.fs" />
    <Compile Include="RestorePhysicalReplayFixture.fs" />
    <Compile Include="RestoreProducePhysicalChecks.fs" />
    <Compile Include="RestoreProducePhysicalTests.fs" />
    <Compile Include="RestoreProduceAdvancedPairTests.fs" />
    <Compile Include="ActorGrantStoreTests.fs" />
    <Compile Include="ActorGrantLookupTests.fs" />
    <Compile Include="ActorBoundCoreTestSupport.fs" />
    <Compile Include="ActorBoundCoreTests.fs" />
    <Compile Include="BackupCaptureFenceTests.fs" />
    <Compile Include="BackupCaptureFrameTests.fs" />
    <Compile Include="BackupControlLifetimeTests.fs" />
    <Compile Include="BackupCaptureClaimsTests.fs" />
    <Compile Include="BackupCapturePathsTests.fs" />
    <Compile Include="BackupCaptureEvidenceFixture.fs" />
    <Compile Include="BackupCaptureSessionTests.fs" />
    <Compile Include="CaseListAuthorityTests.fs" />
    <Compile Include="CaseListCapacityTests.fs" />
    <Compile Include="ActorBoundReplayTests.fs" />
    <Compile Include="ActorBoundRecoveryTests.fs" />
    <Compile Include="RecoveryListAuthorityTests.fs" />
    <Compile Include="ManagedCopyEventHashTests.fs" />
    <Compile Include="ManagedCopySignerTestSupport.fs" />
    <Compile Include="ManagedCopySignerAssertions.fs" />
    <Compile Include="ManagedCopySignerTests.fs" />
    <Compile Include="ManagedCopySignerPurposeTests.fs" />
    <Compile Include="ManagedCopyAttestationFixture.fs" />
    <Compile Include="ManagedCopyAuditTestSupport.fs" />
    <Compile Include="ManagedCopyIngestTests.fs" />
    <Compile Include="InstallationLossRetirementFixture.fs" />
    <Compile Include="InstallationLossRetirementCrashFixture.fs" />
    <Compile Include="InstallationLossRetirementCommitFault.fs" />
    <Compile Include="InstallationLossRetirementDenialAudit.fs" />
    <Compile Include="InstallationLossRetirementTests.fs" />
    <Compile Include="InstallationLossRetirementReadOrder.fs" />
    <Compile Include="InstallationLossRetirementCrashTests.fs" />
    <Compile Include="InstallationLossRetirementStalePairTests.fs" />
    <Compile Include="BackupCaptureEvidenceProcess.fs" />
    <Compile Include="BackupCaptureEvidenceTests.fs" />
    <Compile Include="ManagedCopyTransitionRejectionTests.fs" />
    <Compile Include="RestoreProduceSignerTests.fs" />
    <Compile Include="WriterHandoffApprovalTests.fs" />
    <Compile Include="RealDataActivationPlanFixture.fs" />
    <Compile Include="RealDataActivationApprovalTests.fs" />
    <Compile Include="RealDataActivationApprovalUncertaintyTests.fs" />
    <Compile Include="RealDataActivationMechanicsSupport.fs" />
    <Compile Include="RealDataActivationMechanicsTests.fs" />
    <Compile Include="WriterHandoffRevocationTests.fs" />
    <Compile Include="WriterHandoffHolderTests.fs" />
    <Compile Include="WriterHandoffDocuments.fs" />
    <Compile Include="WriterHandoffPrimaryFixture.fs" />
    <Compile Include="ManagedCopyInventoryFixture.fs" />
    <Compile Include="InstallationLossRetirementProcessTests.fs" />
    <Compile Include="ManagedCopyPhysicalProofFixture.fs" />
    <Compile Include="WriterHandoffProcessFixture.fs" />
    <Compile Include="WriterHandoffSyntheticVerifier.fs" />
    <Compile Include="WriterHandoffProtocolAssertions.fs" />
    <Compile Include="WriterHandoffProtocolPreparation.fs" />
    <Compile Include="WriterHandoffProtocolCommit.fs" />
    <Compile Include="WriterHandoffProtocolTests.fs" />
    <Compile Include="WriterHandoffAbortProcessFixture.fs" />
    <Compile Include="WriterHandoffAbortRetryAssertions.fs" />
    <Compile Include="WriterHandoffAbortScenario.fs" />
    <Compile Include="WriterHandoffAbortStages.fs" />
    <Compile Include="WriterHandoffAbortProtocolTests.fs" />
    <Compile Include="ManagedCopyInventoryDocuments.fs" />
    <Compile Include="ManagedCopyInventoryTests.fs" />
    <Compile Include="ManagedCopyVerifiedDeletionFixture.fs" />
    <Compile Include="ManagedCopyVerifiedDeletionCompletion.fs" />
    <Compile Include="ManagedCopyVerifiedDeletionTests.fs" />
    <Compile Include="ManagedCopyVerifiedRestoreTests.fs" />
    <Compile Include="ManagedCopyPhysicalProcessDocuments.fs" />
    <Compile Include="ManagedCopyPhysicalOwnerSetup.fs" />
    <Compile Include="ManagedCopyPhysicalOwnerRefusals.fs" />
    <Compile Include="ManagedCopyPhysicalOwnerTransition.fs" />
    <Compile Include="BackupHealthCommitInterleaving.fs" />
    <Compile Include="BackupHealthSourceMaterial.fs" />
    <Compile Include="BackupHealthSourceDocuments.fs" />
    <Compile Include="BackupHealthReconciliationTests.fs" />
    <Compile Include="BackupHealthRuntimeActorRaceDocuments.fs" />
    <Compile Include="BackupHealthRuntimeActorRaceFacts.fs" />
    <Compile Include="ManagedCopyPhysicalVerificationFixture.fs" />
    <Compile Include="ManagedCopyPhysicalProcessTests.fs" />
    <Compile Include="BackupHealthRuntimeActorRaceTests.fs" />
    <Compile Include="BackupCapturePhysicalPrivate.fs" />
    <Compile Include="BackupCapturePhysicalDocuments.fs" />
    <Compile Include="BackupCapturePhysicalSigners.fs" />
    <Compile Include="BackupCapturePhysicalProcess.fs" />
    <Compile Include="BackupCapturePhysicalTests.fs" />
    <Compile Include="RestoreProduceSourceEvidence.fs" />
    <Compile Include="RestoreProduceSourceDocuments.fs" />
    <Compile Include="RestoreProduceInventoryDigestChecks.fs" />
    <Compile Include="RestoreProduceSignerFixture.fs" />
    <Compile Include="RestoreProduceSignedPairChecks.fs" />
    <Compile Include="RestoreProduceSignedPairFixture.fs" />
    <Compile Include="RestoreProduceSignedPairTests.fs" />
    <Compile Include="RestoreWriterHandoffFencePins.fs" />
    <Compile Include="RestoreWriterHandoffPrivateFixture.fs" />
    <Compile Include="RestoreWriterHandoffQualificationFixture.fs" />
    <Compile Include="RestoreWriterHandoffTypedSettlement.fs" />
    <Compile Include="RestoreWriterHandoffTypedFixture.fs" />
    <Compile Include="RestoreWriterHandoffContext.fs" />
    <Compile Include="RestorePhysicalWalRetention.fs" />
    <Compile Include="RestoreWriterHandoffOwnerApprovals.fs" />
    <Compile Include="RestoreWriterHandoffPhysicalPreparation.fs" />
    <Compile Include="RestoreWriterHandoffPhysicalSettlement.fs" />
    <Compile Include="RestoreWriterHandoffPhysicalIsolation.fs" />
    <Compile Include="RestoreWriterHandoffPhysicalTests.fs" />
    <Compile Include="RestoreFencedTailSourceDocuments.fs" />
    <Compile Include="RestoreFencedTailInputTests.fs" />
    <Compile Include="BackupHealthSourceTests.fs" />
    <Compile Include="RestoreFencedTailPhysicalTests.fs" />
    <Compile Include="WriterActivationSyntheticTail.fs" />
    <Compile Include="WriterActivationTests.fs" />
    <Compile Include="WriterActivationCrashTests.fs" />
    <Compile Include="IndependentHostProbeFixture.fs" />
    <Compile Include="IndependentHostProbeTests.fs" />
    <Compile Include="IndependentHostTopologyTests.fs" />
    <Compile Include="ManagedCopyKindTests.fs" />
    <Compile Include="ManagedCopyCryptoTests.fs" />
    <Compile Include="ManagedCopyWitnessTipTests.fs" />
    <Compile Include="ActorManagementTests.fs" />
    <Compile Include="CaseLifecycleStoreFixture.fs" />
    <Compile Include="CaseLifecycleStoreTests.fs" />
    <Compile Include="PreparationHoldRetentionTests.fs" />
    <Compile Include="MutationDisclosureFixture.fs" />
    <Compile Include="MutationDisclosureTests.fs" />
    <Compile Include="CaseListBlockedTimingTests.fs" />
    <Compile Include="CaseErasureFenceTests.fs" />
    <Compile Include="CaseLifecycleAuditTests.fs" />
    <Compile Include="CaseLifecycleReconcileTests.fs" />
    <Compile Include="CaseLifecycleCapacityTests.fs" />
    <Compile Include="CaseErasurePendingTests.fs" />
    <Compile Include="CaseErasureFencesTests.fs" />
    <Compile Include="CaseErasurePurgeTimestampAssertions.fs" />
    <Compile Include="CaseErasurePurgeReviewAssertions.fs" />
    <Compile Include="CaseErasurePurgeTests.fs" />
    <Compile Include="CaseTombstoneAuthorityTests.fs" />
    <Compile Include="CaseWitnessPayloadPruneEvidence.fs" />
    <Compile Include="CaseWitnessPayloadPruneControls.fs" />
    <Compile Include="CaseWitnessPayloadPruneTests.fs" />
    <Compile Include="CaseWitnessPayloadPruneRotation.fs" />
    <Compile Include="CaseWitnessPayloadPruneRetryTests.fs" />
    <Compile Include="CaseWitnessPayloadPruneAuditTests.fs" />
    <Compile Include="CaseWitnessPruneFunctionTests.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalFixture.fs" />
    <Compile Include="CaseTombstoneTerminalApprovalTests.fs" />
    <Compile Include="CaseTombstoneTerminalUncertaintyTests.fs" />
    <Compile Include="CaseTombstoneTerminalAuditTamperTests.fs" />
    <Compile Include="CaseTombstoneTerminalOwnerTests.fs" />
    <Compile Include="DatabaseTerminalCopyAbsenceTests.fs" />
    <Compile Include="DatabaseTerminalCopyAbsenceProcessTests.fs" />
    <Compile Include="DatabaseWitnessPruneProcessInputs.fs" />
    <Compile Include="DatabaseWitnessPruneProcessTests.fs" />
    <Compile Include="ManagedCopyHoldTests.fs" />
    <Compile Include="CaseErasurePurgeAuditTests.fs" />
    <Compile Include="CaseErasureArtifactTests.fs" />
    <Compile Include="ProductExportEventChainTests.fs" />
    <Compile Include="ManagedCopyAdoptionApprovalTests.fs" />
    <Compile Include="ManagedCopyAdoptionDocuments.fs" />
    <Compile Include="ManagedCopyAdoptionSource.fs" />
    <Compile Include="ManagedCopyAdoptedExternalSource.fs" />
    <Compile Include="ManagedCopyAdoptionFixture.fs" />
    <Compile Include="ManagedCopyExternalPublicationDocuments.fs" />
    <Compile Include="ManagedCopyExternalPublicationFixture.fs" />
    <Compile Include="ManagedCopyAdoptedExternalCase.fs" />
    <Compile Include="ManagedCopyExternalPublicationTests.fs" />
    <Compile Include="ManagedCopyExternalPublicationPruneTests.fs" />
    <Compile Include="ManagedCopyExternalPublicationProcessTests.fs" />
    <Compile Include="ManagedCopyAdoptionOwnerTests.fs" />
    <Compile Include="ManagedCopyAdoptedProductTests.fs" />
    <Compile Include="ManagedCopyAdoptedExternalAdoption.fs" />
    <Compile Include="ManagedCopyAdoptedAbsenceCheck.fs" />
    <Compile Include="ManagedCopyAdoptedAbsenceDocuments.fs" />
    <Compile Include="ManagedCopyAdoptedDeletionProcess.fs" />
    <Compile Include="ManagedCopyAdoptedDeletionRequest.fs" />
    <Compile Include="ManagedCopyAdoptedDeletionFixture.fs" />
    <Compile Include="ManagedCopyAdoptedTransitionTests.fs" />
    <Compile Include="ManagedCopyAdoptionProcessTests.fs" />
    <Compile Include="CaseWitnessPayloadPruneExportTests.fs" />
    <Compile Include="CaseErasurePurgeAdmissionTests.fs" />
    <Compile Include="FreshBaselineTests.fs" />
    <Compile Include="BaselineRefusalTests.fs" />
    <Compile Include="RecoveryProcessTests.fs" />
    <Compile Include="RecoveryRaceTests.fs" />
    <Compile Include="RecoveryEvidenceTests.fs" />
    <Compile Include="RecoveryLifecycleAuthorityTests.fs" />
    <Compile Include="TerminalCapacityTests.fs" />
    <Compile Include="RecoveryStateTests.fs" />
    <Compile Include="RecoveryCancellationFixture.fs" />
    <Compile Include="RecoveryCancellationTests.fs" />
    <Compile Include="AdministrationCompletionTests.fs" />
    <Compile Include="Suite.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ClaimCore.Domain/ClaimCore.Domain.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.Application/ClaimCore.Application.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.Database/ClaimCore.Database.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.HostSecurity/ClaimCore.HostSecurity.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.RecordFormat/ClaimCore.RecordFormat.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.Postgres/ClaimCore.Postgres.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.Witness/ClaimCore.Witness.fsproj" />
    <ProjectReference Include="../../src/ClaimCore.Hosting/ClaimCore.Hosting.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.MTP" PrivateAssets="all" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="NSec.Cryptography" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
  <Import Project="../../src/ClaimCore.HostSecurity/HostSecurity.Native.targets" />
</Project>
