namespace ClaimCore.Docs

[<RequireQualifiedAccess>]
module FrontendTestCatalog =
    let private vitestPart1 =
        set
            [
                "aborts a stale page load before appending a newer cursor page"
                "accepts the matching generated definition fingerprint"
                "associates optional field errors and supports password text input"
                "clears claimant definition state when the server rejects or mismatches assets"
                "closes recovery detail, confirm, and import dialogs without dispatching mutations"
                "coalesces duplicate page loads for one in-flight cursor"
                "coalesces duplicate preparation activation while retention is pending"
                "coalesces duplicate recovery retention for the same previewed bytes"
                "copies safe values and provides an accessible fallback when clipboard access is unavailable"
                "discards an aborted definition response when session epoch changes"
                "discards an aborted keyed read instead of replacing its newer response"
                "fails a malformed authenticated session and leaves invalid mutation calls inert"
                "fails closed on malformed delivery and validates recovery export"
                "fails closed when the server definition is rejected or has a different Web fingerprint"
                "fails immediately when the embedding document omits the application root"
                "generated contract corpora > accepts every production CLI branch and rejects malformed or cross-endpoint values"
                "generated contract corpora > accepts generated Web host values and rejects every malformed or cross-endpoint value"
                "gives simultaneous current and historical case fields distinct heading IDs"
                "keeps a failed history page request-local without erasing current case data"
                "keeps a non-reviewable retained Prepare exact and directs Recovery"
                "keeps an unknown recovery result explicit and directs inspection"
                "keeps existing references immutable and delegates a reviewed commit"
                "keeps generated endpoint inventory callable and presents suspicious Unicode defensively"
                "keeps invalid reducer transitions inert and records a completed receipt"
                "keeps missing case lookup and non-full history entries out of case presentation"
                "keeps recovery confirm dialog accessible before dispatch"
                "keeps recovery import dialog accessible before retention"
                "keeps the anonymous token after a rejected credential so login can be retried"
                "lists, reloads, pages, selects and opens cases through typed list outcomes"
                "locks navigation and logout while a prepared mutation is dispatched"
                "maps every JSON endpoint to v2 and preserves nullable cursors and mutation identity"
                "metadata-driven descriptor rendering > renders descriptor labels and all supplied field values without client-side normalization"
                "metadata-driven dirty command behavior > keeps a prepared operation in recovery and asks before discarding a dirty command switch"
                "metadata-driven drafts > derives command fields, prefill and a canonical draft without a browser command registry"
                "metadata-driven drafts > uses descriptor-only presentation hints"
                "metadata-driven operation acceptance > prepares, reviews, and accepts an operation with React Aria modal semantics"
                "models definite rejection and unknown outcomes without allowing a dispatched mutation to regress"
                "mounts the Web v2 browser root"
                "names idempotent recovery outcomes and leaves downloads without outcome messages"
                "navigates dashboard case, operation and recovery surfaces without hidden business dispatch"
                "offers one explicit exact-ID Prepare retry after lost response"
                "opens a metadata-derived command from Dashboard's current-case transition"
            ]

    let private vitestPart2 =
        set
            [
                "operation editor dialogs and render branches > changes a dirty command only after the discard confirmation"
                "operation editor dialogs and render branches > closes the discard dialog through its accessible cancel action"
                "operation editor dialogs and render branches > keeps a dirty command when the discard dialog is cancelled"
                "operation editor dialogs and render branches > keeps a prepared command for recovery through the review action"
                "operation editor dialogs and render branches > keeps the editor when the review dialog is cancelled"
                "operation editor dialogs and render branches > renders the OPEN reference input and delegates an unprepared close"
                "operation editor support decoding > classifies every delivery lock state"
                "operation editor support decoding > selects only prepared and accepted typed outcome variants"
                "operation editor transport outcomes > focuses and describes a named authored field after core rejection"
                "operation editor transport outcomes > keeps review open when a malformed prepared result omits its exact digest"
                "operation editor transport outcomes > locks the editor and directs recovery after an uncertain prepare delivery"
                "operation editor transport outcomes > makes the review modal non-dismissable while submission is dispatched"
                "operation editor transport outcomes > preserves only recovery direction after an uncertain submit delivery"
                "operation editor transport outcomes > renders an accepted receipt and delegates its return action"
                "operation editor transport outcomes > shows a definite prepare rejection without creating recovery uncertainty"
                "operation editor transport outcomes > shows a definite submit rejection after preserving the prepared identity"
                "rejects JSON-prefix spoofing and accepts an exact JSON media type with parameters"
                "rejects technical preparation details on an accepted Prepare replay"
                "renders a login form with disabled submission until anonymous antiforgery is available"
                "renders a neutral shell while definition admission is pending"
                "renders a recoverable session failure and invokes its refresh action"
                "renders absent and suspicious accepted values without changing the recorded text"
                "renders an exact accepted Prepare replay as a definite receipt"
                "renders anonymous login and authenticated dashboard paths"
                "renders direct observed-accepted recovery receipts"
                "renders loading and refreshable session failures"
                "renders observed recovery details and leaves only permitted server actions enabled"
                "renders recovery import controls and lets the page reload without mutation"
                "renders recovery list state, invokes inspection, and pages through a cursor"
                "renders the loading shell before local session discovery completes"
                "reports a failed list as a request-local error without manufacturing rows"
                "reports a found observation without a receipt as a protocol failure"
                "reports absent and malformed operation observations without leaving stale receipts"
                "reports malformed pages, malformed inspections, rejected imports, and invalid exports"
                "requires fresh inspection before retrying a submission-started preparation"
                "requires one exact attachment filename and matching UTF-8 filename parameter"
            ]

    let private vitestPart3 =
        set
            [
                "retains an exact id until a retained preparation is edited, then starts a new id"
                "returns an accepted open operation to Dashboard through its committed transition"
                "returns from a selected case through Dashboard's detail-back transition"
                "rotates the retained operation ID when only an OPEN reference is changed"
                "routes dashboard list selections and the new-case command into the typed editor"
                "sends bounded raw imports with generated media type and digest header"
                "shows current fields, server command labels, full expandable history and retryable history pages"
                "shows logout transport failure as retriable and clears it after a session refresh"
                "submits a retained operation ID and digest only once under duplicate confirmation"
                "surfaces invalid snapshots after login and logout responses"
                "treats a typed missing history as an empty read rather than a transport error"
                "uses an exact operation lookup result and clears absent lookup presentation"
                "uses generated v2 paths and typed endpoint outcomes"
                "uses inspected accepted evidence to remove stale list mutation actions"
                "v2 Recovery import and export > exports the validated filename then retains previewed envelope material without submission"
                "v2 Recovery import and export > retains canonical-record previews and reports rejected recovery pages"
                "v2 Recovery view > inspects and dismisses only a server-advertised unsubmitted preparation"
                "v2 Recovery view > keeps a completed non-acceptance out of the accepted receipt path"
                "v2 Recovery view > renders a definite resolve receipt instead of treating it as transport uncertainty"
                "v2 session lifecycle > hydrates, signs in, renders v2 definition, and signs out through the anonymous snapshot"
            ]

    let vitest = Set.unionMany [ vitestPart1; vitestPart2; vitestPart3 ]

    let browser =
        set
            [
                "bounds repeated published login admission and recovers after its window"
                "contains keyboard focus and returns it after safely dismissing a prepared review"
                "exports and retains both exact recovery artifact formats through published Web"
                "focuses and describes the named field after a published core rejection"
                "keeps published login, editor, review, receipt and history accessible at narrow and zoomed viewports"
                "prefills metadata fields and confirms dirty command changes before review"
                "preserves operation identity after a dropped published submit response"
                "publishes open, amendment, decision, withdrawal, full history and operation lookup"
                "publishes payment, correction, close and reopen with current-case parity"
                "recovers an exact preparation after its published response is dropped"
                "rejects retired routes and malformed published Web v2 admission before mutation"
                "resolves and dismisses exact preparations with observed server state"
                "rotates a retained OPEN identity when only its target reference changes"
                "shows exact case and operation misses without implying a failed mutation"
                "uses the published v2 login boundary and accessible case workspace"
            ]
