[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $SbomPath,
    [Parameter(Mandatory)][string] $OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$sbom = Get-Content -LiteralPath $SbomPath -Raw | ConvertFrom-Json -Depth 30

$components = @(
    $sbom.components |
        Where-Object { -not $_.name.StartsWith("ClaimCore", [StringComparison]::Ordinal) } |
        Sort-Object name, version
)
if ($components.Count -eq 0) { throw "The .NET SBOM has no third-party components." }

$groups = [ordered]@{}
foreach ($component in $components) {
    if ([string]::IsNullOrWhiteSpace($component.name) -or [string]::IsNullOrWhiteSpace($component.version)) {
        throw "A .NET SBOM component lacks identity."
    }
    $licenses = @($component.licenses | ForEach-Object { $_.license.id })
    if ($licenses.Count -ne 1 -or [string]::IsNullOrWhiteSpace($licenses[0])) {
        throw "$($component.name) lacks one exact redistribution license."
    }

    $licensePath = switch ($licenses[0]) {
        "MIT" { Join-Path $PSScriptRoot "licenses/MIT-DOTNET.txt" }
        "PostgreSQL" { Join-Path $PSScriptRoot "licenses/PostgreSQL-NPGSQL.txt" }
        default { throw "$($component.name) uses an unreviewed .NET redistribution license." }
    }
    $licenseText = [IO.File]::ReadAllText($licensePath).Trim()
    if (-not $groups.Contains($licenseText)) { $groups[$licenseText] = [Collections.Generic.List[string]]::new() }

    $upstream = @(
        $component.externalReferences |
            Where-Object { $_.type -in "website", "vcs" } |
            ForEach-Object url |
            Select-Object -First 1
    )
    $source = if ($upstream.Count -eq 1) { $upstream[0] } else { "Not supplied" }
    $groups[$licenseText].Add("Package: $($component.name)@$($component.version)`nDeclared license: $($licenses[0])`nUpstream: $source")
}

$separator = "`n`n--------------------------------------------------------------------------------`n`n"
$sections = foreach ($entry in $groups.GetEnumerator()) {
    (@($entry.Value) -join "`n`n") + "`n`n" + $entry.Key
}
$header = @(
    "ClaimCore .NET — third-party notices",
    "",
    "Generated from the locked production dependency graph. Do not edit this file manually.",
    "ClaimCore itself is licensed separately under Apache-2.0 in LICENSE.",
    ""
) -join "`n"
$contents = $header + "`n" + ($sections -join $separator) + "`n"
[IO.File]::WriteAllText($OutputPath, $contents, [Text.UTF8Encoding]::new($false))
